import type { SearchVertical } from "../../types";
import type { VerticalSchema } from "./types";

const COMMON_CONDITION_OPTIONS = ["new", "used", "Not sure"];

const AUTO_ENGINE_FAMILIES = [
    "Caterpillar C12",
    "Caterpillar C15",
    "Cummins ISX",
    "Detroit DD15",
    "Not sure",
];

const AUTO_MAKES = [
    "Toyota",
    "Honda",
    "Ford",
    "Chevrolet",
    "Nissan",
    "BMW",
    "Not sure",
];

const VERTICAL_SCHEMAS: Record<SearchVertical, VerticalSchema> = {
    auto_parts: {
        vertical: "auto_parts",
        keywords: [
            "cylinder head",
            "alternator",
            "radiator",
            "starter",
            "head gasket",
            "brake",
            "engine",
            "transmission",
            "turbo",
            "injector",
            "caterpillar",
            "cummins",
            "detroit",
        ],
        slots: [
            {
                field: "engine_model",
                question: "Which engine model/type does this part need to fit?",
                reason: "Fitment is the strongest precision signal for auto parts.",
                priority: "highValue",
                optionGeneration: "mixed",
                taxonomyOptions: AUTO_ENGINE_FAMILIES,
            },
            {
                field: "part_type",
                question: "What exact part type are you looking for?",
                reason: "Part type disambiguates broad automotive queries.",
                priority: "highValue",
                optionGeneration: "mixed",
                taxonomyOptions: ["cylinder head", "alternator", "starter", "radiator", "Not sure"],
            },
            {
                field: "make",
                question: "What vehicle or equipment make is this for?",
                reason: "Make narrows candidate compatibility quickly.",
                priority: "highValue",
                optionGeneration: "mixed",
                taxonomyOptions: AUTO_MAKES,
            },
            {
                field: "model",
                question: "What model is this for?",
                reason: "Model is key for compatibility.",
                priority: "mediumValue",
                optionGeneration: "result_entities",
            },
            {
                field: "year_range",
                question: "What year range should this fit?",
                reason: "Year is important for fitment-specific parts.",
                priority: "mediumValue",
                optionGeneration: "query_entities",
            },
            {
                field: "condition",
                question: "Do you want new or used?",
                reason: "Condition improves shopping relevance and price alignment.",
                priority: "lowValue",
                optionGeneration: "taxonomy",
                taxonomyOptions: COMMON_CONDITION_OPTIONS,
            },
        ],
    },
    vehicles: {
        vertical: "vehicles",
        keywords: [
            "for sale",
            "mileage",
            "vin",
            "sedan",
            "truck",
            "suv",
            "motorcycle",
            "car",
            "vehicle",
        ],
        slots: [
            {
                field: "make",
                question: "What make are you looking for?",
                reason: "Vehicle make is the top-level disambiguator.",
                priority: "highValue",
                optionGeneration: "mixed",
                taxonomyOptions: AUTO_MAKES,
            },
            {
                field: "model",
                question: "Which model are you interested in?",
                reason: "Model gives precision for inventory matching.",
                priority: "highValue",
                optionGeneration: "result_entities",
            },
            {
                field: "year_range",
                question: "What year range do you want?",
                reason: "Year range improves relevance.",
                priority: "mediumValue",
                optionGeneration: "query_entities",
            },
            {
                field: "condition",
                question: "Do you want new or used?",
                reason: "Condition impacts both pricing and inventory quality.",
                priority: "lowValue",
                optionGeneration: "taxonomy",
                taxonomyOptions: COMMON_CONDITION_OPTIONS,
            },
        ],
    },
    electronics: {
        vertical: "electronics",
        keywords: [
            "iphone",
            "macbook",
            "laptop",
            "gpu",
            "cpu",
            "monitor",
            "headphones",
            "camera",
            "tablet",
            "smartphone",
        ],
        slots: [
            {
                field: "phone_focus",
                question: "What matters most for the phone you want?",
                reason: "Phone searches get better fast when we know the buyer's priority.",
                priority: "highValue",
                optionGeneration: "taxonomy",
                taxonomyOptions: [
                    "Best value",
                    "Camera quality",
                    "Battery life",
                    "Gaming / performance",
                    "Simple / compact",
                    "Not sure",
                ],
                askOnBroadQuery: true,
                triggerKeywords: ["phone", "smartphone", "cell phone", "mobile phone"],
                satisfiedByQueryKeywords: [
                    "budget",
                    "cheap",
                    "camera",
                    "battery",
                    "gaming",
                    "performance",
                    "compact",
                    "small",
                    "simple",
                ],
            },
            {
                field: "camera_use",
                question: "What kind of camera are you shopping for?",
                reason: "Camera intent separates very different product families.",
                priority: "highValue",
                optionGeneration: "taxonomy",
                taxonomyOptions: [
                    "Beginner / easy to use",
                    "Photography",
                    "Video / content creation",
                    "Travel / compact",
                    "Professional",
                    "Not sure",
                ],
                askOnBroadQuery: true,
                triggerKeywords: ["camera", "cameras"],
                satisfiedByQueryKeywords: [
                    "beginner",
                    "photo",
                    "photography",
                    "video",
                    "vlog",
                    "content",
                    "compact",
                    "travel",
                    "professional",
                    "pro",
                    "mirrorless",
                    "dslr",
                ],
            },
            {
                field: "usage_profile",
                question: "What kind of laptop are you looking for?",
                reason: "Broad laptop searches improve when we know the intended use.",
                priority: "highValue",
                optionGeneration: "taxonomy",
                taxonomyOptions: [
                    "Cost-effective",
                    "Everyday use",
                    "High performance",
                    "Creative / visual work",
                    "Gaming / heavy performance",
                    "Not sure",
                ],
                askOnBroadQuery: true,
                triggerKeywords: ["laptop", "notebook", "computer", "pc"],
                satisfiedByQueryKeywords: [
                    "budget",
                    "cheap",
                    "affordable",
                    "everyday",
                    "daily",
                    "performance",
                    "gaming",
                    "creative",
                    "visual",
                    "editing",
                    "design",
                    "workstation",
                ],
            },
            {
                field: "brand",
                question: "Which brand do you prefer?",
                reason: "Brand is usually the main precision signal in electronics.",
                priority: "highValue",
                optionGeneration: "mixed",
                taxonomyOptions: ["Apple", "Samsung", "Dell", "HP", "Lenovo", "Asus", "Not sure"],
            },
            {
                field: "model",
                question: "Which model are you searching for?",
                reason: "Model narrows similarly named products.",
                priority: "highValue",
                optionGeneration: "result_entities",
            },
            {
                field: "condition",
                question: "Do you want new or used?",
                reason: "Condition affects price and warranty expectations.",
                priority: "mediumValue",
                optionGeneration: "taxonomy",
                taxonomyOptions: COMMON_CONDITION_OPTIONS,
            },
            {
                field: "priceIntent",
                question: "What price tier are you aiming for?",
                reason: "Price intent helps ranking when product family is broad.",
                priority: "lowValue",
                optionGeneration: "taxonomy",
                taxonomyOptions: ["cheap", "mid", "premium", "Not sure"],
            },
        ],
    },
    fashion: {
        vertical: "fashion",
        keywords: ["dress", "shirt", "sneakers", "jacket", "pants", "hoodie", "shoe", "bag"],
        slots: [
            {
                field: "dress_shoe_style",
                question: "What kind of dress shoes do you need?",
                reason: "Dress-shoe searches are much more useful when we know the occasion or style.",
                priority: "highValue",
                optionGeneration: "taxonomy",
                taxonomyOptions: [
                    "Formal / office",
                    "Wedding / event",
                    "Loafers",
                    "Oxfords / lace-up",
                    "Comfort-first",
                    "Not sure",
                ],
                askOnBroadQuery: true,
                triggerKeywords: [
                    "dress shoe",
                    "dress shoes",
                    "oxford",
                    "oxfords",
                    "loafer",
                    "loafers",
                ],
                satisfiedByQueryKeywords: [
                    "formal",
                    "office",
                    "wedding",
                    "event",
                    "loafer",
                    "loafers",
                    "oxford",
                    "oxfords",
                    "comfort",
                ],
            },
            {
                field: "shoe_type",
                question: "What kind of shoes are you looking for?",
                reason: "Shoe style is usually the fastest way to narrow a broad shoe search.",
                priority: "highValue",
                optionGeneration: "taxonomy",
                taxonomyOptions: ["Sporty", "Casual", "Dress", "Boots", "Sandals", "Not sure"],
                askOnBroadQuery: true,
                triggerKeywords: [
                    "shoe",
                    "shoes",
                    "sneaker",
                    "sneakers",
                    "boot",
                    "boots",
                    "heel",
                    "heels",
                    "loafer",
                    "loafers",
                    "sandal",
                    "sandals",
                ],
                satisfiedByQueryKeywords: [
                    "sport",
                    "sporty",
                    "athletic",
                    "running",
                    "casual",
                    "dress",
                    "boot",
                    "boots",
                    "loafer",
                    "loafers",
                    "heel",
                    "heels",
                    "sandal",
                    "sandals",
                ],
            },
            {
                field: "brand",
                question: "Any specific brand you want?",
                reason: "Brand is often the key shopping intent signal for fashion.",
                priority: "highValue",
                optionGeneration: "mixed",
                taxonomyOptions: ["Nike", "Adidas", "Zara", "H&M", "Uniqlo", "Not sure"],
            },
            {
                field: "size",
                question: "What size are you looking for?",
                reason: "Size is critical to reduce unusable results.",
                priority: "highValue",
                optionGeneration: "taxonomy",
                taxonomyOptions: ["XS", "S", "M", "L", "XL", "Not sure"],
            },
            {
                field: "condition",
                question: "Do you want new or used?",
                reason: "Condition is often important for apparel marketplaces.",
                priority: "mediumValue",
                optionGeneration: "taxonomy",
                taxonomyOptions: COMMON_CONDITION_OPTIONS,
            },
        ],
    },
    home: {
        vertical: "home",
        keywords: ["sofa", "couch", "sectional", "table", "chair", "bed", "mattress", "lamp", "appliance", "kitchen"],
        slots: [
            {
                field: "sofa_style",
                question: "What kind of sofa are you looking for?",
                reason: "Sofa searches vary a lot by living-space and comfort needs.",
                priority: "highValue",
                optionGeneration: "taxonomy",
                taxonomyOptions: [
                    "Loveseat / small space",
                    "Sectional / family size",
                    "Sleeper sofa",
                    "Reclining / comfort",
                    "Modern / statement",
                    "Not sure",
                ],
                askOnBroadQuery: true,
                triggerKeywords: ["sofa", "couch", "sectional"],
                satisfiedByQueryKeywords: [
                    "loveseat",
                    "sectional",
                    "sleeper",
                    "reclining",
                    "recliner",
                    "modern",
                    "small",
                    "apartment",
                ],
            },
            {
                field: "category",
                question: "Which home category is this for?",
                reason: "Category narrows broad home queries.",
                priority: "highValue",
                optionGeneration: "taxonomy",
                taxonomyOptions: ["furniture", "appliances", "decor", "kitchen", "Not sure"],
            },
            {
                field: "brand",
                question: "Any preferred brand?",
                reason: "Brand helps ranking and quality matching.",
                priority: "mediumValue",
                optionGeneration: "result_entities",
            },
            {
                field: "condition",
                question: "Do you want new or used?",
                reason: "Condition strongly impacts pricing and expectations.",
                priority: "mediumValue",
                optionGeneration: "taxonomy",
                taxonomyOptions: COMMON_CONDITION_OPTIONS,
            },
        ],
    },
    sports: {
        vertical: "sports",
        keywords: ["bike", "bicycle", "golf", "tennis", "baseball", "basketball", "soccer", "fitness"],
        slots: [
            {
                field: "bike_type",
                question: "What kind of bike are you after?",
                reason: "Bike type is usually the main distinction in a broad bike search.",
                priority: "highValue",
                optionGeneration: "taxonomy",
                taxonomyOptions: [
                    "Road bike",
                    "Mountain bike",
                    "Hybrid / commuter",
                    "Electric bike",
                    "BMX / kids",
                    "Not sure",
                ],
                askOnBroadQuery: true,
                triggerKeywords: ["bike", "bicycle"],
                satisfiedByQueryKeywords: [
                    "road",
                    "mountain",
                    "hybrid",
                    "commuter",
                    "electric",
                    "ebike",
                    "bmx",
                    "kids",
                ],
            },
            {
                field: "category",
                question: "What type of sports item are you looking for?",
                reason: "Sports queries are often broad without equipment type.",
                priority: "highValue",
                optionGeneration: "taxonomy",
                taxonomyOptions: ["fitness", "cycling", "golf", "team sports", "Not sure"],
            },
            {
                field: "brand",
                question: "Do you have a preferred brand?",
                reason: "Brand improves result quality for many equipment types.",
                priority: "mediumValue",
                optionGeneration: "result_entities",
            },
            {
                field: "condition",
                question: "Do you want new or used?",
                reason: "Condition affects quality and price range expectations.",
                priority: "mediumValue",
                optionGeneration: "taxonomy",
                taxonomyOptions: COMMON_CONDITION_OPTIONS,
            },
        ],
    },
    other: {
        vertical: "other",
        keywords: [],
        slots: [
            {
                field: "category",
                question: "Which category best matches what you need?",
                reason: "Category clarifies broad unknown queries.",
                priority: "highValue",
                optionGeneration: "taxonomy",
                taxonomyOptions: ["electronics", "fashion", "home", "sports", "auto_parts", "Not sure"],
            },
            {
                field: "brand",
                question: "Any brand preference?",
                reason: "Brand can still reduce broad result sets.",
                priority: "mediumValue",
                optionGeneration: "result_entities",
            },
        ],
    },
    general: {
        vertical: "general",
        keywords: [],
        slots: [
            {
                field: "category",
                question: "What category are you searching in?",
                reason: "Category is the most useful first clarification for broad queries.",
                priority: "highValue",
                optionGeneration: "taxonomy",
                taxonomyOptions: ["electronics", "fashion", "home", "sports", "auto_parts", "vehicles", "Not sure"],
            },
            {
                field: "brand",
                question: "Do you have a preferred brand?",
                reason: "Brand can significantly improve precision across categories.",
                priority: "mediumValue",
                optionGeneration: "result_entities",
            },
            {
                field: "priceIntent",
                question: "What price tier are you aiming for?",
                reason: "Price intent is a useful fallback for broad shopping queries.",
                priority: "lowValue",
                optionGeneration: "taxonomy",
                taxonomyOptions: ["cheap", "mid", "premium", "Not sure"],
            },
        ],
    },
};

export function getVerticalSchema(vertical: SearchVertical): VerticalSchema {
    return VERTICAL_SCHEMAS[vertical] ?? VERTICAL_SCHEMAS.general;
}

export function getAllVerticalSchemas(): VerticalSchema[] {
    return Object.values(VERTICAL_SCHEMAS);
}
